Intro:
  pages:
    intro/preface: "Preface"
    intro/tokenized-protocol-messages: "Protocol Overview - Messages"
    intro/tokenized-protocol-asset-types: "Protocol Overview - Asset Types"
Main Concepts:
  pages:
    main-concepts/tokens: "Tokens"
    main-concepts/smart-contracts: "Smart Contracts"
    main-concepts/action-mechanism: "Action Mechanism"
    main-concepts/rules: "Rules"
    main-concepts/transactions: "Transactions"
Order of Operations:
  pages:
    order-of-operations/contract: "Contract"
    order-of-operations/asset: "Asset"
Actions:
  pages:
    protocol/contract-offer: "Contract offer"
    protocol/contract-formation: "Contract Formation"
    protocol/contract-amendment: "Contract Amendment"
    protocol/static-contract-formation: "Static Contract Formation"
    protocol/asset-definition: "Asset Definition"
    protocol/asset-creation: "Asset Creation"
    protocol/asset-modification: "Asset Modification"
    protocol/transfer: "transfer"
    protocol/settlement: "Settlement"
    protocol/initiative: "Initiative"
    protocol/referendum: "Referendum"
    protocol/vote: "Vote"
    protocol/ballot-cast: "Ballot Cast"
    protocol/ballot-counted: "Ballot Counted"
    protocol/result: "Result"
    protocol/order: "Order"
    protocol/freeze: "Freeze"
    protocol/thaw: "Thaw"
    protocol/confiscation: "Confiscation"
    protocol/reconciliation: "Reconciliation"
    protocol/establishment: "Establishment"
    protocol/addition: "Addition"
    protocol/alteration: "Alteration"
    protocol/removal: "Removal"
    protocol/message: "Message"
    protocol/rejection: "Rejection"
Asset Types:
  pages:
    asset/coupon: "Coupons"
    asset/loyalty-points: "Loyalty Points"
    asset/membership: "Membership"
    asset/share-common: "Common Share"
    asset/ticket-admission: "Admission Ticket"
    asset/currency: "Currency"
Examples:
  pages:
